version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - ./src/config/database.env
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - ./src/config/database.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
